### ISSUE TITLE
Login on a separate page?

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#25]
Nic and I  were discussing: should the login page on the app be on the HomePage, or should it have its own separate page?

**Comment by ninamariepeterson** [comment]
I think we could go either way.  I like the look of the login but I don't think it is intuitive that it goes with the class schedule.  I think probably a separate page would be good (that is how most schools that I have seen have it) or putting the login where the class list would be so that they know they need to login to see their schedule.

**Comment by nicdford** [comment]
Fixed in #32
