### ISSUE TITLE
Handle Class Schedule Loading Times

### ISSUE THREAD

**Issue by AustinHaugerud** [lcsc-capstone/lcsc-ionic-app#30]
The process of the loading the class schedule data from WarriorWeb is proving to take a noticeable amount of time, anywhere from 1-5 seconds from my numerous tests. This wait time is likely unavoidable. To get this data, the app has to go through several steps

- Load the authentication data from secure storage (IO operation)
- Load the WarriorWeb login page
- Asynchronously inject JS scripts to fill in the login fields and click the login button.
- Wait for the schedule page to load.
- Asynchronously inject a JS script to scrape the json object that contains the schedule data. This object is actually quite large.
- Parse the json after the JS script injection completes and returns, then process it into course items, finally filling the list.

A lot of these operations are things that can't be optimized out, they are simply slow to complete. I think our best bet will be of course not loading the schedule more often than necessary, and if the user accesses the page when it needs to load, provide a loading animation or something of that sort.

**Comment by clblamires** [comment]
There are a few things we can do for this, potentially:

1. Store the user's schedule into an Angular Service. The service would store the schedule and its details, and the app would draw those data from the service rather than online. In this way, the app only pulls the data when it opens, and not going between pages.

2. Ionic has a [loading controller](https://ionicframework.com/docs/api/components/loading/LoadingController/) that would be useful while waiting for the data to download and save into the service.

Anyone else have thoughts/ideas?

**Comment by dneverson** [comment]
@AustinHaugerud can this issue be closed?
