### ISSUE TITLE
Menu and Home

### ISSUE THREAD

**Issue by ninamariepeterson** [lcsc-capstone/lcsc-ionic-app#39]
The menu button is now centered in the middle instead of on the left.

**Comment by clblamires** [comment]
Fixed #39
The issue was in /src/pages/home/home.scss - someone had set the width of buttons to 93% (line 21) but that applied to *all* buttons on the page, including the menu button. Whoever readjusts the home page's buttons, please use classes when modifying an element. Never modify the base element itself.
